version: '3'
services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HISTORY_FILE=calculator_history.txt
  volumes:
      - /path/to/host/history_file:/app/calculator_history.txt
